-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\commrshdl\ErrorGen.vhd
-- Created: 2024-04-06 12:58:26
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- dataOut                       ce_out        1
-- startOut                      ce_out        1
-- endOut                        ce_out        1
-- validOut                      ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ErrorGen
-- Source Path: commrshdl/ErrorGen
-- Hierarchy Level: 0
-- Model version: 9.5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ErrorGen IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        startIn                           :   IN    std_logic;
        endIn                             :   IN    std_logic;
        validIn                           :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        dataOut                           :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        startOut                          :   OUT   std_logic;
        endOut                            :   OUT   std_logic;
        validOut                          :   OUT   std_logic
        );
END ErrorGen;


ARCHITECTURE rtl OF ErrorGen IS

  -- Component Declarations
  COMPONENT ErrorGen_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          StartIn                         :   IN    std_logic;
          EndIn                           :   IN    std_logic;
          ValidIn                         :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          StartOut                        :   OUT   std_logic;
          EndOut                          :   OUT   std_logic;
          ValidOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ErrorGen_block
    USE ENTITY work.ErrorGen_block(rtl);

  -- Signals
  SIGNAL ErrorGen_out1                    : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL ErrorGen_out2                    : std_logic;
  SIGNAL ErrorGen_out3                    : std_logic;
  SIGNAL ErrorGen_out4                    : std_logic;

BEGIN
  u_ErrorGen : ErrorGen_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              DataIn => dataIn,  -- uint8
              StartIn => startIn,
              EndIn => endIn,
              ValidIn => validIn,
              DataOut => ErrorGen_out1,  -- uint8
              StartOut => ErrorGen_out2,
              EndOut => ErrorGen_out3,
              ValidOut => ErrorGen_out4
              );

  startOut <= ErrorGen_out2;

  endOut <= ErrorGen_out3;

  validOut <= ErrorGen_out4;

  ce_out <= clk_enable;

  dataOut <= ErrorGen_out1;

END rtl;

