-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\commrshdl\RS_Encoder_pkg.vhd
-- Created: 2024-04-06 12:58:06
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE RS_Encoder_pkg IS
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
END RS_Encoder_pkg;

